### PR TITLE
有 _or 前缀的即认为是 or 语句，这样可以支持多个 or 条件

### PR DESCRIPTION
**Pull request by zhanghongnian**

### CODE REVIEW

**Comment by caibirdme** [comment]
LGTM, add some documents please

**Comment by zhanghongnian** [comment]
any suppest？

**Comment by caibirdme** [comment]
Should remove the sort which I've pointed out in the review

**Comment by zhanghongnian** [comment]
fixed

**Comment by caibirdme** [comment]
Thx for your contribution

**Pull request merged**
