### PR TITLE
支持常用insert类型ignore replace

### PR DESCRIPTION
**Pull request by guangxuewu**

### CODE REVIEW

**Comment by caibirdme** [comment]
Could you please add some related unit tests?

**Comment by guangxuewu** [comment]
> Could you please add some related unit tests?

ok

**Comment by caibirdme** [comment]
你如果有时间的话可以把文档补齐一下，如果没时间的话我可能会晚些时候才会来补齐文档，然后merge

**Comment by guangxuewu** [comment]
> 你如果有时间的话可以把文档补齐一下，如果没时间的话我可能会晚些时候才会来补齐文档，然后merge

帮忙看看还需要补充说明吗

**Comment by caibirdme** [comment]
@guangxuewu Thx for your contribute, But I think it would be better to remove the go.mod and go.sum file because gendry only depends on the standard library, all the other packages are for testing.

**Comment by guangxuewu** [comment]
> @guangxuewu Thx for your contribute, But I think it would be better to remove the go.mod and go.sum file because gendry only depends on the standard library, all the other packages are for testing.
add go.mod is to support go1.11

**Comment by caibirdme** [comment]
@guangxuewu 感谢。主要是依赖都是测试包，不要依赖直接拉下来不影响正常使用，所以觉得没必要添加mod

**Pull request merged**
