### PR TITLE
对Scanner增加UnmarshalBinary的支持。

### PR DESCRIPTION
**Pull request by leeeboo**
如果scan的target是一个struct，且其中的一个字断在数据库中是一个json的string，那么支持在scan的时候实现UnmarshalBinary这个接口解析这个字断。例子：

type TestInfo struct {
    StrData         string      `ddb:"str_data"`
    StructData      *StructData `ddb:"struct_data"` //这个字断在db中是char类型，存储的是一个json字符串（{"foo":"foo","bar":"bar"}）
}

type StructData struct {
    Foo string `json:"foo"`
    Bar string `json:"bar"`
}

func (this *StructData) UnmarshalDB(data []byte) error {
    return json.Unmarshal(data, this)
}

### CODE REVIEW

**Comment by caibirdme** [comment]
Thx for your contribution, It's a great idea to support types implementing their own unmarshal method.
Besides invoking `UnmarshalByte` for non-nil objects, we'd also allocate memory for the nil objects and do the `UnmarshalByte` later. Also I think using such a deep embedded reflection is a little complex, and the returned error is ambiguous because we can't learn from the error that this is caused by UnmarshalByte itself rather than type mismatch.
I hope you don't mind my changing your code and I add some test cases for this.
Doc is also updated.

**Comment by leeeboo** [comment]
@caibirdme Thx.

**Comment by caibirdme** [comment]
Looking forward to your further contribution 😄

**Comment by brzyangg** [comment]
这块如果是一个字段类型是一个数组的话，可以直接marshal 上去吗？

**Comment by caibirdme** [comment]
> 这块如果是一个字段类型是一个数组的话，可以直接marshal 上去吗？

你自己实现unmarshal逻辑，至于是数组还是什么，自己在逻辑里判断

**Pull request merged**
